### ISSUE TITLE
Don't create an environment if there is no new migration

### ISSUE THREAD

**Issue by ilyasmez** [contentful/contentful-action#19]
Hello 👋 

Right now a new environment is created even if there is no new migration.
Is there a good reason behind this? Because I think it will better to skip the creation in that case and just return the master environment.
I'm asking because, as you know, Contentful has a very very limited number of environments allowed.

I'd like to get your opinion  first, and I can create a PR if we agree on something (we can also think of adding an optional flag).

**Comment by ilyasmez** [comment]
FYI @Shy @stefanjudis

**Comment by Shy** [comment]
@ilyasmez Thanks for tagging me. I must have missed the notification :|. 

The action is based on our [circleci example](https://github.com/contentful-labs/continous-delivery-environments-example) which is designed more as a tutorial than a production out of the box thing you can just use. Since that's a tutorial I take the route of being more verbose rather than less. 

For this action I'd be happy to accept a PR. I would prefer the change to occur via a flag so it wouldn't mess with the workflows of folks already using it.
